vm_size="Standard_D2_v2"
env="production"
dns_cluster="exampleaks1"
mcittt="ccrf2301"
node_count=1
name_node="default"
rg_nametwo="fritz_resource_group"
location_for_azuretwo="West India"
rg_name="salomon_resource_group"
location_for_azure="Canada East"
clusterlist=["ccrf2301mtl","ccrf2301to","ccrf2301van","ccrf2301alb"]
